### ISSUE TITLE
Error when install via npm

### ISSUE THREAD

**Issue by seanlin816** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#1]
I installed using npm install netsuite-fasttrack-toolkit-ss2 --save
I got the following error:
 **Failed at the netsuite-fasttrack-toolkit-ss2@0.2.1 postinstall script 'echo `pwd`;ln -s --backup `pwd`/declarations ../../NFT-SS2-$npm_package_version'.**

Please see the attachment.

![screen shot 2016-10-06 at 12 54 22](https://cloud.githubusercontent.com/assets/2238725/19140966/21829110-8bc4-11e6-8a5e-dd98bb065445.png)

**Comment by ShawnTalbert** [comment]
Fixed in 0.2.2 5ec9e73a9b88568e1846463c60e0aa942d3b7e07, please confirm Sean?

**Comment by ShawnTalbert** [comment]
We'll take no response as a good response. We can reopen if this is still an issue, but it seems to install successfully on other macs around here.

**Comment by ShawnTalbert** [comment]
fyi, v 0.4.2+ has this resolved.

**Comment by seanlin816** [comment]
I am sorry for late response. This is working properly for me. Thank you.
