### ISSUE TITLE
Does this module allow me to connect to Netsuite API via node.js?

### ISSUE THREAD

**Issue by namelus** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#12]
Trying to figure out if this module allows me to connect and run code from node.js, or just allows me to write code in node.js and then upload to NS Suitescript?

**Comment by ShawnTalbert** [comment]
No, this module is meant to make writing SuiteScript easier.

Where it overlaps with NodeJS is that is allows one to write _unit tests_ for SuiteScript that run in NodeJS.

So, you can write and execute isolated unit tests of your SuiteScript code locally via NodeJS.

That is separate from writing SuiteScript itself which runs on the NetSuite platform.

If you are writing a Node app and want to talk to NetSuite SuiteTalk I suggest you utilize an existing SOAP library for node. 
Best of luck!
