### ISSUE TITLE
Importing leads to "Fail to evaluate script: All SuiteScript API Modules are unavailable while executing your define callback."

### ISSUE THREAD

**Issue by donblackowiak** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#13]
Thank you for creating this great module.  I want to use it in my project, but I am unable to run even a simple test without running into Netsuite's "Fail to evaluate script: All SuiteScript API Modules are unavailable while executing your define callback."

This fails to even upload without error above.  This seems so simple. I am hoping it's a simple fix. Thanks!

/**
 * Test file for SuiteScript 2.0
 * (replace 'NFT/' below with the relative path to your NFT-SS2-x.y.z folder)
 * @NApiVersion 2.x
 * @NScriptType Suitelet
 */
define(["require", "exports", "N/log", "/SuiteScripts/NFT-SS2-4.3.0/DataAccess/CustomerBase"], function (require, exports, log, CustomerBase) {
    return {
        onRequest: function (req, resp) {
            log.debug("test", "include CustomerBase module");
        }
    };
});

While This works as expected.

/**
 * @NApiVersion 2.x
 * @NScriptType Suitelet
 */
define(["require", "exports", "N/log"], function (require, exports, log) {
    return {
        onRequest: function (req, resp) {
            log.debug("test", "no module");
        }
    };
});

**Comment by ShawnTalbert** [comment]
How are you submitting the code to the file cabinet? I recommend uploading your working skeleton script first to create your initial script record and deployment. 
Then update the script file via the File Cabinet UI or some external utility - not via copy/paste into the script "edit" display.

NS has (bugs IMHO) rejecting code that works perfectly at runtime.

**Comment by donblackowiak** [comment]
Thank you Shawn.  That did the trick and allowed my test and the included test to work.  So I will proceed creating a skeleton first.

**Comment by ShawnTalbert** [comment]
I do recommend you use TypeScript for the most pleasant experience with NFT
