### ISSUE TITLE
Updating the NetSuiteRecord.nsrecord in BeforeSubmit has no effect

### ISSUE THREAD

**Issue by steveklett** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#29]
Using NFT 5.4.0

This works (record is saved with field 'taxdetailsoverride' checked):
```
  export function beforeSubmit(context: EntryPoints.UserEvent.beforeLoadContext) {
    context.newRecord.setValue({fieldId: 'taxdetailsoverride', value: true})
  }
```

This does not (record is saved with field 'taxdetailsoverride' unchanged):
```
  export function beforeSubmit(context: EntryPoints.UserEvent.beforeLoadContext) {
    const order = new SalesOrder(context.newRecord.id)
    order.nsrecord.setValue({fieldId: 'taxdetailsoverride', value: true})
  }
```

**Comment by ShawnTalbert** [comment]
Hi Steve. in a BeforeSubmit event just pass in the record instance. e.g. 
`const order = new SalesOrder(context.newRecord)`

By passing in the record *id* it _loads_ the sales order, and then you're not `.save()`ing it so nothing happens.

By just passing in the native record reference (`context.newRecord`) NFT just wraps that and uses it directly, which is also best for performance.

**Comment by steveklett** [comment]
Hi Shawn,
I missed the reply but the close message caught my eye.
Your response makes complete sense and I'm sorry I didn't notice that difference myself. I've changed to passing the reference and all is well. Now I need to contribute to add TaxDetail support :)
