### ISSUE TITLE
Dynamic mode no longer working on 5.6.0

### ISSUE THREAD

**Issue by nathaniel-norton** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#35]
When attempting to load a record in dynamic mode I receive an error saying that I've performed an invalid sublist operation.

```
    let opportunityRecord = new Opportunity(recordId, true)
    log.debug('opportunityRecord', opportunityRecord)
```
ERROR:
`SSS_INVALID_SUBLIST_OPERATION`
`You have attempted an invalid sublist or line item operation. You are either trying to access a field on a non-existent line or you are trying to add or remove lines from a static sublist`

This was working on 5.3.0. We recently updated a project to 5.6.0 and then this error showed up.

**Comment by ShawnTalbert** [comment]
5.6.0 did have changes to sublists behind the scenes (improvements?).

@nathaniel-norton  can you please email me a link to the project/script in question so I can take a look?

**Comment by ShawnTalbert** [comment]
I've identified the problem and will patch it for 5.6.1. Turns out this is due to the behind the scenes 'new' feature of handling the _phantom_ line that exists on new records.

**Comment by ShawnTalbert** [comment]
This should be addressed in 5.6.1, please confirm

**Comment by nathaniel-norton** [comment]
@ShawnTalbert The original issue appears to be resolved. However, when working in dynamic mode the `addLine` method doesn't work properly. It throws an error which says `TypeError: Cannot set property "item" of undefined to "XX"`. I'll send you additional details via email.

**Comment by ShawnTalbert** [comment]
Thanks - I'll close this issue continuing on with #36 for addLine()
