### ISSUE TITLE
Question - Set Field Text

### ISSUE THREAD

**Issue by rhackeyexplore** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#7]
Do we have any examples of setting body, sublist and subrecord fields' by text values using NFT for SS2?

**Comment by ShawnTalbert** [comment]
For body fields, you should be able to just add _Text_ to your field name and it will get/set using getText()/setText()

For sublist/subrecord there is no built in magic, so you use the `nsrecord` property on your record instance. e.g. `mycustomer.nsrecord.XXX()`

**Comment by ShawnTalbert** [comment]
Here's an example of declaring you want the subsidiary field on the customer record as text:

```typescript
   class Customer extends CustomerBase {
      @FieldType.freeformtext
      subsidiaryText:string
   }
```
If we need this for sublist and/or subrecords let's add them as separate 'feature request' issues?
